import { Box, Center, Container, Flex } from "@chakra-ui/react";
import Head from "next/head";

import About from "../component/about";
import PictureOfMe from "../component/picture";
import Skills from "../component/skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sebastians Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <Box>
        <Center
          pos={{ base: "static", md: "fixed" }}
          left={0}
          top={0}
          w={{ base: "100%", md: "50%" }}
          maxW={"2000"}
          justify={"center"}
          minH={{ base: "auto,", md: "100vh" }}
          my={{ base: "20", md: "auto" }}
        >
          <PictureOfMe />
        </Center>
        <Flex
          align="center"
          justify={{ base: "center", md: "space-around" }}
          direction={{ base: "column", md: "row" }}
          wrap="no-wrap"
          minH={{ base: "auto,", md: "100vh" }}
          my={{ base: "20", md: "auto" }}
        >
          <Box w={{ base: "100%", md: "50%" }} />

          <Box w={{ base: "100%", md: "50%" }} px={"5vw"}>
            <About />
          </Box>
        </Flex>
        <Flex
          align="center"
          justify={{ base: "center", md: "space-around" }}
          direction={{ base: "column", md: "row" }}
          wrap="no-wrap"
          minH={{ base: "auto,", md: "100vh" }}
          my={{ base: "20", md: "auto" }}
        >
          <Box w={{ base: "100%", md: "50%" }} />

          <Box w={{ base: "100%", md: "50%" }} px={"5vw"}>
            <Skills />
          </Box>
        </Flex>
      </Box>
    </>
  );
}
