import { Box, Center, Container, Flex, HStack, Stack } from "@chakra-ui/react";
import Head from "next/head";

import About from "../component/about";
import PictureOfMe from "../component/picture";
import References from "../component/ref";
import Skills from "../component/skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sebastians Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        scrollSnapType={{ base: "none", md: "y mandatory" }}
        overflowY={"scroll"}
        h={"100vh"}
        scrollBehavior={"smooth"}
      >
        <Container maxW="1080px" p={"10px"}>
          <Stack direction={{ base: "column", md: "row" }}>
            <Center
              pos={{ base: "static", md: "fixed" }}
              bottom={{ base: "auto", md: "50vh" }}
              mb={{ base: "0", md: "-200" }}
              ml={{ base: "0", md: "-20px" }}
              height={"420px"}
            >
              <PictureOfMe></PictureOfMe>
            </Center>
            <Stack
              spacing={8}
              pl={{ base: "auto", md: "400" }}
              w={"full"}
              p={0}
              zIndex={99}
            >
              <Box scrollSnapAlign={"start"}>
                <About />
              </Box>
              <Box scrollSnapAlign={"start"}>
                <Skills />
              </Box>
              <Box scrollSnapAlign={"start"} id="refs">
                <References />
              </Box>
            </Stack>
          </Stack>
        </Container>
      </Box>
    </>
  );
}
